### ISSUE TITLE
Missing SQL file and launcher issue

### ISSUE THREAD

**Issue by gentle-shao** [PrinceFroggy/GoKart#1]
It looks like the emulator needs MySQL to provide data for client and there should be a sql file in directory.
Another question is about the launcher,I couldn't find anything like "server_ip" in it.

**Comment by PrinceFroggy** [comment]
These files were grabbed quickly before deletion.

I am just re hosting these files for anyone interested.

I am not 100% sure if you had to edit launcher to your server ip.
